export { default as BkCommentAudio  } from "./comment.svg"
export { default as BkNextAudio } from "./nextaudio.svg"
export { default as BkPrevAudio } from "./prevaudio.svg"
export { default as BkPlay } from "./play.svg"
export { default as BkPlayAudio } from "./playaudio.svg"
export { default as BkUnlock } from "./unlock.svg"
export { default as BkWave } from "./wave.svg"
